image: raatiniemi/android-environment:latest

stages:
  - test
  - build

test:
  stage: test
  script:
    - bin/test
  tags:
    - docker

sonar:
  stage: test
  script:
    - bin/sonar
  only:
    - tags
  tags:
    - docker

build:
  stage: build
  script:
    - bin/build
  tags:
    - docker
